### ISSUE TITLE
Pretrained model link not working?

### ISSUE THREAD

**Issue by peacherwu** [DerWaldi/youtube-video-face-swap#2]
Your link of pretrained model is not a valid zip file:
[https://anonfile.com/Ec8a61ddbf/Angela_Swift.zip](url)

**Comment by DerWaldi** [comment]
Hi peacherwu,
I'm guessing you're trying to directly wget the url.
Since it is hosted on one of the free hosters, you need to open the link in your browser and download it there.

**Comment by peacherwu** [comment]
Wonderful! How could I miss that?!

**Comment by peacherwu** [comment]
Wonderful! How could I miss that?!
